lambda_ent: 0.1
lambda_src_joint: 1.0
lambda_trg_joint: 1.0
lambda_src_feat_adv: 0.0001
lambda_trg_feat_adv: 0.0001
lambda_src_vat: 0.0
lambda_trg_vat: 1.0
lambda_consis_src: 1.0
lambda_consis_trg: 1.0

eps_vat: 0.5
std: 1.0
nb_jc: 1
nb_cc: 1
nb_e: 1

net_name: small_cnn
lr_scheme: ADAM
max_lr: 0.001
drop_prob: 0.05

instance_norm: False
is_bn: True
is_curriculum: False

b_source: 100
b_target: 100
num_epochs: 150
